<?php

/**
 * @file
 * Contains wizard_form.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wizard_form_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wizard_form module.
    case 'help.page.wizard_form':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Wizard form to create users') . '</p>';
      return $output;

    default:
  }
}
